# Generated by Django 4.1.13 on 2024-04-14 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Critère',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Défi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prénom', models.CharField(max_length=255)),
                ('spécialité', models.CharField(choices=[('DSI', 'DSI'), ('RSS', 'RSS'), ('CNM', 'CNM')], max_length=255)),
                ('niveau', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Jery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prénom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lienGit', models.CharField(max_length=255)),
                ('dateSoumission', models.DateTimeField()),
                ('status', models.CharField(choices=[('soumis', 'Soumis'), ('évalué', 'Évalué')], max_length=7)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('défi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.défi')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('motDePasse', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('étudiant', 'Étudiant'), ('organisateur', 'Organisateur'), ('jury', 'Jury')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Évaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('commentaires', models.TextField()),
                ('jery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jery')),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.soumission')),
            ],
        ),
        migrations.CreateModel(
            name='Équipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEquipe', models.CharField(max_length=255)),
                ('nombreMembres', models.IntegerField()),
                ('adjointID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjoint_teams', to='myapp.utilisateur')),
                ('leadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_teams', to='myapp.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='soumission',
            name='équipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.équipe'),
        ),
        migrations.CreateModel(
            name='Résultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreTotal', models.IntegerField()),
                ('équipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.équipe')),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.critère')),
                ('défi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.défi')),
                ('équipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.équipe')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('adjoint', 'Adjoint'), ('membre', 'Membre')], max_length=7)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
                ('équipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.équipe')),
            ],
        ),
        migrations.CreateModel(
            name='GrilleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.IntegerField()),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.critère')),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.défi')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('membre_jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jery')),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.soumission')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.défi')),
                ('membre_jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jery')),
            ],
        ),
    ]
