# Generated by Django 2.2.22 on 2024-04-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20240414_0940'),
        ('myapp', '0005_auto_20240414_1022'),
    ]

    operations = [
    ]
