# Generated by Django 2.2.22 on 2024-04-15 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20240414_1053'),
        ('myapp', '0005_auto_20240414_0947'),
    ]

    operations = [
    ]
